# Basic Example

## First, import the needed libraries and files

You only need the bond list and the coordinates of the nodes in a network to be able to use ‍`rigidpy‍`. I have added a sample network here. The bond list contains information about nodes that are connected. For example (0,1) means nodes 0 and 1 are connected. The coordinates (in $2$D) is an array of $x$ and $y$ coordinates for all the nodes. The number of rows in the array shows the label of node in the network (starting from zero).

In [10]:
import networkx as nx
import numpy as np
import rigidpy as rp
import matplotlib.pyplot as plt
%matplotlib inline

In [13]:
# list of bond
bonds = np.array([[0,1],[1,2],[0,2]])
# position of nodes
coordinates = coordinates = np.array([[-1,0], [1,0], [0,1]])
# repetition of unit-cell
basis = [[0,0],[0,0]]
# which site is pinned in space
pins = [0]

In [14]:
print (coordinates)

[[-1  0]
 [ 1  0]
 [ 0  1]]


In [15]:
print (bonds)

[[0 1]
 [1 2]
 [0 2]]


## Build a Framework 

Create a `framework` object:

In [17]:
F = rp.framework(coordinates, bonds, basis=basis, pins=pins)

Calculate the rigidity matrix:

In [19]:
print ("rigidity matrix:\n", F.rigidityMatrix())

rigidity matrix:
 [[ 1.         -0.          0.          0.        ]
 [ 0.70710678 -0.70710678 -0.70710678  0.70710678]
 [ 0.          0.          0.70710678  0.70710678]]


Calculate the eigenvalues of Hessian/dynamical matrix:

In [20]:
eigvals, eigvecs = F.eigenSpace(eigvals=(0,3))
print("vibrational eigenvalues:\n",eigvals)

vibrational eigenvalues:
 [-2.22044605e-16  6.33974596e-01  1.00000000e+00  2.36602540e+00]


Note that a system with $N$ sites in $d$ dimensions, has at most $N \times d$ frequencies. However, since one site is pinned in this example, the number of frequencies is 4. If you specify a larger number, the library will tell you the maximum range:

In [31]:
F.eigenSpace(eigvals=(0,6))

ValueError: Requested eigenvalue indices are not valid. Valid range is [0, 3] and start <= end, but start=0, end=6 is given